/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/provenance/environment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Environment */
        get: operations["environment_api_v1_provenance_environment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/router/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide */
        post: operations["decide_api_v1_router_decide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Experiments */
        get: operations["list_experiments_api_v1_experiments_get"];
        put?: never;
        /** Create Experiment */
        post: operations["create_experiment_api_v1_experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation/retrieval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate Retrieval */
        post: operations["evaluate_retrieval_api_v1_evaluation_retrieval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion/formats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Supported Formats */
        get: operations["supported_formats_api_v1_ingestion_formats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpora": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Corpora */
        get: operations["list_corpora_api_v1_corpora_get"];
        put?: never;
        /** Create Corpus */
        post: operations["create_corpus_api_v1_corpora_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpora/{corpus_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Corpus */
        get: operations["get_corpus_api_v1_corpora__corpus_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpora/{corpus_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_corpora__corpus_id__documents_get"];
        put?: never;
        /**
         * Ingest Documents
         * @description Ingest a batch. Returns the ingestion record: one outcome per file, and the new version.
         */
        post: operations["ingest_documents_api_v1_corpora__corpus_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpora/{corpus_id}/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_corpora__corpus_id__documents__document_id__get"];
        put?: never;
        post?: never;
        /**
         * Remove Document
         * @description Remove from the next corpus version. Earlier versions keep the document.
         */
        delete: operations["remove_document_api_v1_corpora__corpus_id__documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/document-versions/{version_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chunks */
        get: operations["list_chunks_api_v1_document_versions__version_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpora/{corpus_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_api_v1_corpora__corpus_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpora/{corpus_id}/versions/{version}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version Changes */
        get: operations["version_changes_api_v1_corpora__corpus_id__versions__version__changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpora/{corpus_id}/ingestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ingestions */
        get: operations["list_ingestions_api_v1_corpora__corpus_id__ingestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpora/{corpus_id}/retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retrieve
         * @description Rank chunks of one corpus version for a query. Defaults to the current version.
         */
        post: operations["retrieve_api_v1_corpora__corpus_id__retrieve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Bm25Params */
        Bm25Params: {
            /**
             * K1
             * @description Term-frequency saturation
             * @default 1.2
             */
            k1: number;
            /**
             * B
             * @description Chunk-length normalisation
             * @default 0.75
             */
            b: number;
        };
        /** Body_ingest_documents_api_v1_corpora__corpus_id__documents_post */
        Body_ingest_documents_api_v1_corpora__corpus_id__documents_post: {
            /**
             * Files
             * @description One or more .txt, .md or .pdf files
             */
            files: string[];
        };
        /** Chunk */
        Chunk: {
            /** Id */
            id: string;
            /** Document Version Id */
            document_version_id: string;
            /** Chunking Hash */
            chunking_hash: string;
            /** Ordinal */
            ordinal: number;
            /** Text */
            text: string;
            /**
             * Char Start
             * @description Offset into the extracted text (inclusive)
             */
            char_start: number;
            /**
             * Char End
             * @description Offset into the extracted text (exclusive)
             */
            char_end: number;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** ChunkPage */
        ChunkPage: {
            /** Document Version Id */
            document_version_id: string;
            /** Chunking Hash */
            chunking_hash: string;
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["Chunk"][];
        };
        /** ChunkingConfig */
        "ChunkingConfig-Input": {
            /** @default recursive */
            strategy: components["schemas"]["ChunkingStrategy"];
            /**
             * Chunk Size
             * @description Max characters
             * @default 1000
             */
            chunk_size: number;
            /**
             * Chunk Overlap
             * @description Characters shared with previous
             * @default 150
             */
            chunk_overlap: number;
        };
        /** ChunkingConfig */
        "ChunkingConfig-Output": {
            /** @default recursive */
            strategy: components["schemas"]["ChunkingStrategy"];
            /**
             * Chunk Size
             * @description Max characters
             * @default 1000
             */
            chunk_size: number;
            /**
             * Chunk Overlap
             * @description Characters shared with previous
             * @default 150
             */
            chunk_overlap: number;
        };
        /**
         * ChunkingStrategy
         * @enum {string}
         */
        ChunkingStrategy: "recursive" | "fixed";
        /** ComponentHealth */
        ComponentHealth: {
            /** Name */
            name: string;
            state: components["schemas"]["ComponentState"];
            /** Detail */
            detail: string;
        };
        /**
         * ComponentState
         * @enum {string}
         */
        ComponentState: "ok" | "not_configured" | "error";
        /**
         * ContentOrigin
         * @description Where a piece of information came from. Every value shown to a user carries one.
         * @enum {string}
         */
        ContentOrigin: "retrieved" | "inferred" | "generated" | "measured" | "simulated";
        /** Corpus */
        Corpus: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            chunking: components["schemas"]["ChunkingConfig-Output"];
            /**
             * Version
             * @description 0 = empty; +1 per content change
             * @default 0
             */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CorpusCreate */
        CorpusCreate: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            chunking?: components["schemas"]["ChunkingConfig-Input"];
        };
        /** CorpusStats */
        CorpusStats: {
            /** Document Count */
            document_count: number;
            /** Chunk Count */
            chunk_count: number;
            /** Total Bytes */
            total_bytes: number;
            /** Total Chars */
            total_chars: number;
            last_ingestion: components["schemas"]["IngestionRecord"] | null;
        };
        /** CorpusSummary */
        CorpusSummary: {
            corpus: components["schemas"]["Corpus"];
            stats: components["schemas"]["CorpusStats"];
        };
        /**
         * CorpusVersion
         * @description An immutable snapshot: which document versions the corpus contained.
         */
        CorpusVersion: {
            /** Corpus Id */
            corpus_id: string;
            /** Version */
            version: number;
            /** Ingestion Id */
            ingestion_id: string | null;
            /** Document Count */
            document_count: number;
            /**
             * Added
             * @default 0
             */
            added: number;
            /**
             * Modified
             * @default 0
             */
            modified: number;
            /**
             * Removed
             * @default 0
             */
            removed: number;
            /**
             * Unchanged
             * @default 0
             */
            unchanged: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * Document
         * @description A logical document, identified within its corpus by filename. Content lives in versions.
         */
        Document: {
            /** Id */
            id: string;
            /** Corpus Id */
            corpus_id: string;
            /** Filename */
            filename: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DocumentDetail */
        DocumentDetail: {
            document: components["schemas"]["Document"];
            /**
             * Versions
             * @description All versions, oldest first
             */
            versions: components["schemas"]["DocumentVersion"][];
            /**
             * Current Version Id
             * @description Version in the corpus's current version; null if the document was removed
             */
            current_version_id: string | null;
        };
        /** DocumentSummary */
        DocumentSummary: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Version Count */
            version_count: number;
            current: components["schemas"]["DocumentVersion"];
        };
        /** DocumentVersion */
        DocumentVersion: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /** Version */
            version: number;
            /** Filename */
            filename: string;
            /** Media Type */
            media_type: string;
            /** Content Sha256 */
            content_sha256: string;
            /** Byte Size */
            byte_size: number;
            /** Parser */
            parser: string;
            extraction_status: components["schemas"]["ExtractionStatus"];
            /** Extraction Warnings */
            extraction_warnings: string[];
            /** Text Chars */
            text_chars: number;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EnvironmentResponse */
        EnvironmentResponse: {
            environment: components["schemas"]["EnvironmentSnapshot"];
        };
        /** EnvironmentSnapshot */
        EnvironmentSnapshot: {
            /** Rag Forge Version */
            rag_forge_version: string;
            /** Python Version */
            python_version: string;
            /** Platform */
            platform: string;
            /** Git Commit */
            git_commit: string | null;
            /** Packages */
            packages: {
                [key: string]: string;
            };
        };
        /** Experiment */
        Experiment: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Hypothesis
             * @default
             */
            hypothesis: string;
            /** Corpus Id */
            corpus_id: string | null;
            /** Configuration Ids */
            configuration_ids: string[];
            /** @default draft */
            status: components["schemas"]["ExperimentStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ExperimentCreate */
        ExperimentCreate: {
            /** Name */
            name: string;
            /**
             * Hypothesis
             * @default
             */
            hypothesis: string;
            /** Corpus Id */
            corpus_id?: string | null;
        };
        /** ExperimentRun */
        ExperimentRun: {
            /** Id */
            id: string;
            /** Experiment Id */
            experiment_id: string;
            /** Configuration Id */
            configuration_id: string;
            /** Config Hash */
            config_hash: string;
            /** @default queued */
            status: components["schemas"]["ExperimentStatus"];
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Provenance Id */
            provenance_id: string | null;
        };
        /**
         * ExperimentStatus
         * @enum {string}
         */
        ExperimentStatus: "draft" | "queued" | "running" | "completed" | "failed";
        /**
         * ExtractionStatus
         * @enum {string}
         */
        ExtractionStatus: "complete" | "partial";
        /**
         * FileOutcome
         * @enum {string}
         */
        FileOutcome: "added" | "modified" | "unchanged" | "duplicate" | "rejected" | "removed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Components */
            components: components["schemas"]["ComponentHealth"][];
        };
        /** IngestionFileResult */
        IngestionFileResult: {
            /** Filename */
            filename: string;
            outcome: components["schemas"]["FileOutcome"];
            /** Byte Size */
            byte_size: number | null;
            /** Content Sha256 */
            content_sha256: string | null;
            /** Media Type */
            media_type: string | null;
            /** Parser */
            parser: string | null;
            /** Document Id */
            document_id: string | null;
            /** Document Version Id */
            document_version_id: string | null;
            /** Duplicate Of */
            duplicate_of: string | null;
            /** Duplicate Of Filename */
            duplicate_of_filename: string | null;
            /** Chunk Count */
            chunk_count: number | null;
            /** Error */
            error: string | null;
            /** Warnings */
            warnings: string[];
        };
        /**
         * IngestionRecord
         * @description Provenance of one ingestion operation. Immutable once written.
         */
        IngestionRecord: {
            /** Id */
            id: string;
            /** Corpus Id */
            corpus_id: string;
            status: components["schemas"]["IngestionStatus"];
            /** Version Before */
            version_before: number;
            /** Version After */
            version_after: number;
            /** Files */
            files: components["schemas"]["IngestionFileResult"][];
            chunking: components["schemas"]["ChunkingConfig-Output"];
            /** Chunking Hash */
            chunking_hash: string;
            environment: components["schemas"]["EnvironmentSnapshot"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
        };
        /**
         * IngestionStatus
         * @enum {string}
         */
        IngestionStatus: "completed" | "no_change" | "failed";
        /** Metric */
        Metric: {
            /** Name */
            name: string;
            /** Value */
            value: number;
            /** K */
            k: number | null;
            /** @default measured */
            origin: components["schemas"]["ContentOrigin"];
        };
        /** NotImplementedDetail */
        NotImplementedDetail: {
            /** Capability */
            capability: string;
            /** Message */
            message: string;
        };
        /** Query */
        Query: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RetrievalEvaluationRequest */
        RetrievalEvaluationRequest: {
            /** Ranked Ids */
            ranked_ids: string[];
            /**
             * Relevance
             * @description Graded relevance judgements; grade > 0 counts as relevant.
             */
            relevance: {
                [key: string]: number;
            };
            /**
             * Ks
             * @default [
             *       1,
             *       5,
             *       10
             *     ]
             */
            ks: number[];
        };
        /** RetrievalEvaluationResponse */
        RetrievalEvaluationResponse: {
            /** Metrics */
            metrics: components["schemas"]["Metric"][];
        };
        /**
         * RetrievalHit
         * @description One retrieved chunk with everything needed to display and trace it.
         */
        RetrievalHit: {
            result: components["schemas"]["RetrievalResult"];
            chunk: components["schemas"]["Chunk"];
            /** Filename */
            filename: string;
            /** Media Type */
            media_type: string;
            /** Document Version */
            document_version: number;
            /** Matched Terms */
            matched_terms: string[];
        };
        /** RetrievalProvenance */
        RetrievalProvenance: {
            /** Corpus Id */
            corpus_id: string;
            /** Corpus Version */
            corpus_version: number;
            /** Chunking Hash */
            chunking_hash: string;
            strategy: components["schemas"]["RetrievalStrategy"];
            /** Retriever */
            retriever: string;
            /** Retriever Config */
            retriever_config: {
                [key: string]: unknown;
            };
            /** Retriever Config Hash */
            retriever_config_hash: string;
            /** Query Terms */
            query_terms: string[];
            /**
             * Statistics
             * @description Retriever-specific, e.g. candidate_chunks, avg_chunk_length, indexed_now
             */
            statistics: {
                [key: string]: number;
            };
            environment: components["schemas"]["EnvironmentSnapshot"];
            /** Elapsed Ms */
            elapsed_ms: number;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
        };
        /** RetrievalRequest */
        RetrievalRequest: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
            /**
             * Version
             * @description Corpus version; default current
             */
            version?: number | null;
            /** @default sparse */
            strategy: components["schemas"]["RetrievalStrategy"];
            bm25?: components["schemas"]["Bm25Params"];
        };
        /** RetrievalResponse */
        RetrievalResponse: {
            query: components["schemas"]["Query"];
            /** Hits */
            hits: components["schemas"]["RetrievalHit"][];
            provenance: components["schemas"]["RetrievalProvenance"];
            /** Warnings */
            warnings: string[];
        };
        /** RetrievalResult */
        RetrievalResult: {
            /** Query Id */
            query_id: string;
            strategy: components["schemas"]["RetrievalStrategy"];
            /** Retriever */
            retriever: string;
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string;
            /** Document Version Id */
            document_version_id: string;
            /** Rank */
            rank: number;
            /** Score */
            score: number;
            /** @default retrieved */
            origin: components["schemas"]["ContentOrigin"];
        };
        /**
         * RetrievalStrategy
         * @enum {string}
         */
        RetrievalStrategy: "sparse" | "dense" | "hybrid" | "metadata" | "graph" | "multi_hop" | "decomposition" | "multimodal";
        /** RouterDecision */
        RouterDecision: {
            /** Id */
            id: string;
            /** Query Id */
            query_id: string;
            /** Policy */
            policy: string;
            /** Query Features */
            query_features: {
                [key: string]: unknown;
            };
            /** Selected Strategies */
            selected_strategies: components["schemas"]["RetrievalStrategy"][];
            /** Rationale */
            rationale: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RouterRequest */
        RouterRequest: {
            /** Corpus Id */
            corpus_id: string;
            /** Query */
            query: string;
            /** Policy */
            policy: string;
        };
        /** RouterResponse */
        RouterResponse: {
            query: components["schemas"]["Query"];
            decision: components["schemas"]["RouterDecision"];
        };
        /** SupportedFormat */
        SupportedFormat: {
            /** Media Type */
            media_type: string;
            /** Extensions */
            extensions: string[];
            /** Parser */
            parser: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionChange */
        VersionChange: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            change: components["schemas"]["FileOutcome"];
            /** Document Version Id */
            document_version_id: string | null;
            /** Previous Document Version Id */
            previous_document_version_id: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    environment_api_v1_provenance_environment_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponse"];
                };
            };
        };
    };
    decide_api_v1_router_decide_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotImplementedDetail"];
                };
            };
        };
    };
    list_experiments_api_v1_experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experiment"][];
                };
            };
        };
    };
    create_experiment_api_v1_experiments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experiment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRun"][];
                };
            };
        };
    };
    evaluate_retrieval_api_v1_evaluation_retrieval_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrievalEvaluationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalEvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    supported_formats_api_v1_ingestion_formats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportedFormat"][];
                };
            };
        };
    };
    list_corpora_api_v1_corpora_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusSummary"][];
                };
            };
        };
    };
    create_corpus_api_v1_corpora_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorpusCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_corpus_api_v1_corpora__corpus_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_corpora__corpus_id__documents_get: {
        parameters: {
            query?: {
                /** @description Defaults to current */
                version?: number | null;
            };
            header?: never;
            path: {
                corpus_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_documents_api_v1_corpora__corpus_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_documents_api_v1_corpora__corpus_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_corpora__corpus_id__documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_document_api_v1_corpora__corpus_id__documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chunks_api_v1_document_versions__version_id__chunks_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_v1_corpora__corpus_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusVersion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_changes_api_v1_corpora__corpus_id__versions__version__changes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionChange"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ingestions_api_v1_corpora__corpus_id__ingestions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_api_v1_corpora__corpus_id__retrieve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrievalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotImplementedDetail"];
                };
            };
        };
    };
}
