/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/provenance/environment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Environment */
        get: operations["environment_api_v1_provenance_environment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/router/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide
         * @description Analyse a query and decide its retrieval configuration without retrieving.
         */
        post: operations["decide_api_v1_router_decide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Experiments */
        get: operations["list_experiments_api_v1_experiments_get"];
        put?: never;
        /** Create Experiment */
        post: operations["create_experiment_api_v1_experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation/retrieval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate Retrieval */
        post: operations["evaluate_retrieval_api_v1_evaluation_retrieval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion/formats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Supported Formats */
        get: operations["supported_formats_api_v1_ingestion_formats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpora": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Corpora */
        get: operations["list_corpora_api_v1_corpora_get"];
        put?: never;
        /** Create Corpus */
        post: operations["create_corpus_api_v1_corpora_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpora/{corpus_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Corpus */
        get: operations["get_corpus_api_v1_corpora__corpus_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpora/{corpus_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_corpora__corpus_id__documents_get"];
        put?: never;
        /**
         * Ingest Documents
         * @description Ingest a batch. Returns the ingestion record: one outcome per file, and the new version.
         */
        post: operations["ingest_documents_api_v1_corpora__corpus_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpora/{corpus_id}/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_corpora__corpus_id__documents__document_id__get"];
        put?: never;
        post?: never;
        /**
         * Remove Document
         * @description Remove from the next corpus version. Earlier versions keep the document.
         */
        delete: operations["remove_document_api_v1_corpora__corpus_id__documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/document-versions/{version_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chunks */
        get: operations["list_chunks_api_v1_document_versions__version_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpora/{corpus_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_api_v1_corpora__corpus_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpora/{corpus_id}/versions/{version}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version Changes */
        get: operations["version_changes_api_v1_corpora__corpus_id__versions__version__changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpora/{corpus_id}/ingestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ingestions */
        get: operations["list_ingestions_api_v1_corpora__corpus_id__ingestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpora/{corpus_id}/retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retrieve
         * @description Rank chunks of one corpus version for a query. Defaults to the current version.
         */
        post: operations["retrieve_api_v1_corpora__corpus_id__retrieve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpora/{corpus_id}/dense-index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dense Index Status */
        get: operations["dense_index_status_api_v1_corpora__corpus_id__dense_index_get"];
        put?: never;
        /**
         * Build Dense Index
         * @description Build the dense index for a corpus version from its stored chunks (no re-ingestion).
         *
         *     Idempotent: returns the ready or in-progress index if there is one. Otherwise starts a build
         *     (202) in the background; poll GET for progress. A failed or stale index is rebuilt.
         */
        post: operations["build_dense_index_api_v1_corpora__corpus_id__dense_index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Bm25Params */
        "Bm25Params-Input": {
            /**
             * K1
             * @description Term-frequency saturation
             * @default 1.2
             */
            k1: number;
            /**
             * B
             * @description Chunk-length normalisation
             * @default 0.75
             */
            b: number;
        };
        /** Bm25Params */
        "Bm25Params-Output": {
            /**
             * K1
             * @description Term-frequency saturation
             * @default 1.2
             */
            k1: number;
            /**
             * B
             * @description Chunk-length normalisation
             * @default 0.75
             */
            b: number;
        };
        /** Body_ingest_documents_api_v1_corpora__corpus_id__documents_post */
        Body_ingest_documents_api_v1_corpora__corpus_id__documents_post: {
            /**
             * Files
             * @description One or more .txt, .md or .pdf files
             */
            files: string[];
        };
        /** Chunk */
        Chunk: {
            /** Id */
            id: string;
            /** Document Version Id */
            document_version_id: string;
            /** Chunking Hash */
            chunking_hash: string;
            /** Ordinal */
            ordinal: number;
            /** Text */
            text: string;
            /**
             * Char Start
             * @description Offset into the extracted text (inclusive)
             */
            char_start: number;
            /**
             * Char End
             * @description Offset into the extracted text (exclusive)
             */
            char_end: number;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** ChunkPage */
        ChunkPage: {
            /** Document Version Id */
            document_version_id: string;
            /** Chunking Hash */
            chunking_hash: string;
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["Chunk"][];
        };
        /** ChunkingConfig */
        "ChunkingConfig-Input": {
            /** @default recursive */
            strategy: components["schemas"]["ChunkingStrategy"];
            /**
             * Chunk Size
             * @description Max characters
             * @default 1000
             */
            chunk_size: number;
            /**
             * Chunk Overlap
             * @description Characters shared with previous
             * @default 150
             */
            chunk_overlap: number;
        };
        /** ChunkingConfig */
        "ChunkingConfig-Output": {
            /** @default recursive */
            strategy: components["schemas"]["ChunkingStrategy"];
            /**
             * Chunk Size
             * @description Max characters
             * @default 1000
             */
            chunk_size: number;
            /**
             * Chunk Overlap
             * @description Characters shared with previous
             * @default 150
             */
            chunk_overlap: number;
        };
        /**
         * ChunkingStrategy
         * @enum {string}
         */
        ChunkingStrategy: "recursive" | "fixed";
        /**
         * Complexity
         * @enum {string}
         */
        Complexity: "simple" | "moderate" | "complex";
        /** ComponentHealth */
        ComponentHealth: {
            /** Name */
            name: string;
            state: components["schemas"]["ComponentState"];
            /** Detail */
            detail: string;
        };
        /**
         * ComponentScore
         * @description How one component retriever saw a fused chunk. Raw scores are never rescaled here.
         */
        ComponentScore: {
            strategy: components["schemas"]["RetrievalStrategy"];
            /**
             * Rank
             * @description Rank in that retriever's candidates; null if absent
             */
            rank: number | null;
            /**
             * Score
             * @description That retriever's own raw score
             */
            score: number | null;
            /**
             * Normalized Score
             * @description Weighted fusion only: min-max normalised score in 0..1
             */
            normalized_score: number | null;
            /**
             * Contribution
             * @description This component's share of the fused score
             */
            contribution: number;
        };
        /**
         * ComponentState
         * @enum {string}
         */
        ComponentState: "ok" | "not_configured" | "error";
        /**
         * ContentOrigin
         * @description Where a piece of information came from. Every value shown to a user carries one.
         * @enum {string}
         */
        ContentOrigin: "retrieved" | "inferred" | "generated" | "measured" | "simulated";
        /** Corpus */
        Corpus: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            chunking: components["schemas"]["ChunkingConfig-Output"];
            /**
             * Version
             * @description 0 = empty; +1 per content change
             * @default 0
             */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CorpusCreate */
        CorpusCreate: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            chunking?: components["schemas"]["ChunkingConfig-Input"];
        };
        /**
         * CorpusQuerySignals
         * @description How the query's terms occur in one corpus version (BM25 analyzer, BM25 statistics).
         */
        CorpusQuerySignals: {
            /** Corpus Id */
            corpus_id: string;
            /** Corpus Version */
            corpus_version: number;
            /** Analyzer */
            analyzer: string;
            /** Chunk Count */
            chunk_count: number;
            /** Terms */
            terms: components["schemas"]["TermStatistic"][];
            /**
             * Coverage
             * @description Share of key terms (bm25_terms if there are none) found in the version
             */
            coverage: number;
            /**
             * Missing Terms
             * @description The terms coverage counts that are absent
             */
            missing_terms: string[];
            /**
             * Mean Idf
             * @description Mean idf of the terms that are present
             */
            mean_idf: number | null;
        };
        /** CorpusStats */
        CorpusStats: {
            /** Document Count */
            document_count: number;
            /** Chunk Count */
            chunk_count: number;
            /** Total Bytes */
            total_bytes: number;
            /** Total Chars */
            total_chars: number;
            last_ingestion: components["schemas"]["IngestionRecord"] | null;
        };
        /** CorpusSummary */
        CorpusSummary: {
            corpus: components["schemas"]["Corpus"];
            stats: components["schemas"]["CorpusStats"];
        };
        /**
         * CorpusVersion
         * @description An immutable snapshot: which document versions the corpus contained.
         */
        CorpusVersion: {
            /** Corpus Id */
            corpus_id: string;
            /** Version */
            version: number;
            /** Ingestion Id */
            ingestion_id: string | null;
            /** Document Count */
            document_count: number;
            /**
             * Added
             * @default 0
             */
            added: number;
            /**
             * Modified
             * @default 0
             */
            modified: number;
            /**
             * Removed
             * @default 0
             */
            removed: number;
            /**
             * Unchanged
             * @default 0
             */
            unchanged: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * DenseIndex
         * @description One build of a dense index for a corpus version under one embedder config.
         */
        DenseIndex: {
            /** Id */
            id: string;
            /** Corpus Id */
            corpus_id: string;
            /** Corpus Version */
            corpus_version: number;
            /** Chunking Hash */
            chunking_hash: string;
            embedder: components["schemas"]["EmbedderInfo"];
            /**
             * Similarity
             * @default cosine
             */
            similarity: string;
            /** @default building */
            status: components["schemas"]["DenseIndexStatus"];
            /**
             * Chunk Count
             * @description Chunks in the corpus version
             */
            chunk_count: number;
            /**
             * Embedded
             * @description Progress: chunks with a vector so far
             * @default 0
             */
            embedded: number;
            /**
             * Reused
             * @description Vectors reused from earlier builds
             * @default 0
             */
            reused: number;
            /**
             * Content Hash
             * @description SHA-256 over chunk ids and exact vector bytes; set when ready
             */
            content_hash: string | null;
            /** Error */
            error: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
        };
        /** DenseIndexBuild */
        DenseIndexBuild: {
            /**
             * Version
             * @description Defaults to the current version
             */
            version?: number | null;
        };
        /**
         * DenseIndexState
         * @description What the UI may promise for a corpus version under the configured embedder.
         * @enum {string}
         */
        DenseIndexState: "ready" | "building" | "failed" | "stale" | "missing";
        /**
         * DenseIndexStatus
         * @enum {string}
         */
        DenseIndexStatus: "building" | "ready" | "failed";
        /**
         * DenseIndexView
         * @description Whether a corpus version has a usable dense index under the configured embedder.
         */
        DenseIndexView: {
            /** Corpus Id */
            corpus_id: string;
            /** Version */
            version: number;
            state: components["schemas"]["DenseIndexState"];
            /** @description Latest build for this version, if any */
            index: components["schemas"]["DenseIndex"] | null;
            embedder: components["schemas"]["EmbedderSpec"];
            /** Embedder Hash */
            embedder_hash: string;
        };
        /**
         * Document
         * @description A logical document, identified within its corpus by filename. Content lives in versions.
         */
        Document: {
            /** Id */
            id: string;
            /** Corpus Id */
            corpus_id: string;
            /** Filename */
            filename: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DocumentDetail */
        DocumentDetail: {
            document: components["schemas"]["Document"];
            /**
             * Versions
             * @description All versions, oldest first
             */
            versions: components["schemas"]["DocumentVersion"][];
            /**
             * Current Version Id
             * @description Version in the corpus's current version; null if the document was removed
             */
            current_version_id: string | null;
        };
        /** DocumentSummary */
        DocumentSummary: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Version Count */
            version_count: number;
            current: components["schemas"]["DocumentVersion"];
        };
        /** DocumentVersion */
        DocumentVersion: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /** Version */
            version: number;
            /** Filename */
            filename: string;
            /** Media Type */
            media_type: string;
            /** Content Sha256 */
            content_sha256: string;
            /** Byte Size */
            byte_size: number;
            /** Parser */
            parser: string;
            extraction_status: components["schemas"]["ExtractionStatus"];
            /** Extraction Warnings */
            extraction_warnings: string[];
            /** Text Chars */
            text_chars: number;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * EmbedderInfo
         * @description The spec plus facts read from the loaded model files.
         */
        EmbedderInfo: {
            spec: components["schemas"]["EmbedderSpec"];
            /** Config Hash */
            config_hash: string;
            /** Dimension */
            dimension: number;
            /** Pooling */
            pooling: string;
            /** Normalize */
            normalize: boolean;
            /** Max Seq Length */
            max_seq_length: number;
            /** Weights Sha256 */
            weights_sha256: string;
        };
        /**
         * EmbedderSpec
         * @description What determines an embedding. Its hash keys every stored vector.
         */
        EmbedderSpec: {
            /**
             * Provider
             * @default onnx-sentence-transformers
             */
            provider: string;
            /**
             * Model
             * @default BAAI/bge-small-en-v1.5
             */
            model: string;
            /**
             * Revision
             * @description Pinned model commit
             * @default 5c38ec7c405ec4b44b94cc5a9bb96e735b38267a
             */
            revision: string;
            /**
             * Query Prefix
             * @description Instruction prepended to queries (not documents), per the model card
             * @default Represent this sentence for searching relevant passages:
             */
            query_prefix: string;
            /**
             * Max Seq Length
             * @description None = the model's own limit
             */
            max_seq_length: number | null;
            /**
             * Batch Size
             * @default 32
             */
            batch_size: number;
        };
        /** EnvironmentResponse */
        EnvironmentResponse: {
            environment: components["schemas"]["EnvironmentSnapshot"];
        };
        /** EnvironmentSnapshot */
        EnvironmentSnapshot: {
            /** Rag Forge Version */
            rag_forge_version: string;
            /** Python Version */
            python_version: string;
            /** Platform */
            platform: string;
            /** Git Commit */
            git_commit: string | null;
            /** Packages */
            packages: {
                [key: string]: string;
            };
        };
        /**
         * EvidenceNeed
         * @enum {string}
         */
        EvidenceNeed: "single_passage" | "multiple_passages";
        /** Experiment */
        Experiment: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Hypothesis
             * @default
             */
            hypothesis: string;
            /** Corpus Id */
            corpus_id: string | null;
            /** Configuration Ids */
            configuration_ids: string[];
            /** @default draft */
            status: components["schemas"]["ExperimentStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ExperimentCreate */
        ExperimentCreate: {
            /** Name */
            name: string;
            /**
             * Hypothesis
             * @default
             */
            hypothesis: string;
            /** Corpus Id */
            corpus_id?: string | null;
        };
        /** ExperimentRun */
        ExperimentRun: {
            /** Id */
            id: string;
            /** Experiment Id */
            experiment_id: string;
            /** Configuration Id */
            configuration_id: string;
            /** Config Hash */
            config_hash: string;
            /** @default queued */
            status: components["schemas"]["ExperimentStatus"];
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Provenance Id */
            provenance_id: string | null;
        };
        /**
         * ExperimentStatus
         * @enum {string}
         */
        ExperimentStatus: "draft" | "queued" | "running" | "completed" | "failed";
        /**
         * ExtractionStatus
         * @enum {string}
         */
        ExtractionStatus: "complete" | "partial";
        /**
         * FileOutcome
         * @enum {string}
         */
        FileOutcome: "added" | "modified" | "unchanged" | "duplicate" | "rejected" | "removed";
        /** FusionDetail */
        FusionDetail: {
            method: components["schemas"]["FusionMethod"];
            /**
             * Score
             * @description Fused score (the hit's result.score unless reranked)
             */
            score: number;
            /** Components */
            components: components["schemas"]["ComponentScore"][];
        };
        /**
         * FusionMethod
         * @enum {string}
         */
        FusionMethod: "rrf" | "weighted";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Components */
            components: components["schemas"]["ComponentHealth"][];
        };
        /** HybridParams */
        "HybridParams-Input": {
            /**
             * Retrievers
             * @description Component strategies to fuse
             */
            retrievers?: components["schemas"]["RetrievalStrategy"][];
            /** @default rrf */
            fusion: components["schemas"]["FusionMethod"];
            /**
             * Rrf K
             * @description RRF smoothing constant
             * @default 60
             */
            rrf_k: number;
            /**
             * Weights
             * @description Weighted fusion only: one weight per component, each 0..1, summing to 1
             */
            weights?: {
                [key: string]: number;
            };
            /**
             * Candidate K
             * @description Candidates requested from each component
             * @default 50
             */
            candidate_k: number;
        };
        /** HybridParams */
        "HybridParams-Output": {
            /**
             * Retrievers
             * @description Component strategies to fuse
             */
            retrievers: components["schemas"]["RetrievalStrategy"][];
            /** @default rrf */
            fusion: components["schemas"]["FusionMethod"];
            /**
             * Rrf K
             * @description RRF smoothing constant
             * @default 60
             */
            rrf_k: number;
            /**
             * Weights
             * @description Weighted fusion only: one weight per component, each 0..1, summing to 1
             */
            weights: {
                [key: string]: number;
            };
            /**
             * Candidate K
             * @description Candidates requested from each component
             * @default 50
             */
            candidate_k: number;
        };
        /** IngestionFileResult */
        IngestionFileResult: {
            /** Filename */
            filename: string;
            outcome: components["schemas"]["FileOutcome"];
            /** Byte Size */
            byte_size: number | null;
            /** Content Sha256 */
            content_sha256: string | null;
            /** Media Type */
            media_type: string | null;
            /** Parser */
            parser: string | null;
            /** Document Id */
            document_id: string | null;
            /** Document Version Id */
            document_version_id: string | null;
            /** Duplicate Of */
            duplicate_of: string | null;
            /** Duplicate Of Filename */
            duplicate_of_filename: string | null;
            /** Chunk Count */
            chunk_count: number | null;
            /** Error */
            error: string | null;
            /** Warnings */
            warnings: string[];
        };
        /**
         * IngestionRecord
         * @description Provenance of one ingestion operation. Immutable once written.
         */
        IngestionRecord: {
            /** Id */
            id: string;
            /** Corpus Id */
            corpus_id: string;
            status: components["schemas"]["IngestionStatus"];
            /** Version Before */
            version_before: number;
            /** Version After */
            version_after: number;
            /** Files */
            files: components["schemas"]["IngestionFileResult"][];
            chunking: components["schemas"]["ChunkingConfig-Output"];
            /** Chunking Hash */
            chunking_hash: string;
            environment: components["schemas"]["EnvironmentSnapshot"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
        };
        /**
         * IngestionStatus
         * @enum {string}
         */
        IngestionStatus: "completed" | "no_change" | "failed";
        /** Metric */
        Metric: {
            /** Name */
            name: string;
            /** Value */
            value: number;
            /** K */
            k: number | null;
            /** @default measured */
            origin: components["schemas"]["ContentOrigin"];
        };
        /** NotImplementedDetail */
        NotImplementedDetail: {
            /** Capability */
            capability: string;
            /** Message */
            message: string;
        };
        /** Query */
        Query: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** QueryAnalysis */
        QueryAnalysis: {
            /** Analyzer */
            analyzer: string;
            /** Analyzer Version */
            analyzer_version: string;
            /**
             * Config Hash
             * @description Hash of the analyzer's weights and thresholds
             */
            config_hash: string;
            /** Query */
            query: string;
            /** Normalized Query */
            normalized_query: string;
            features: components["schemas"]["QueryFeatures"];
            /** Signals */
            signals: components["schemas"]["QuerySignal"][];
            labels: components["schemas"]["QueryLabels"];
            corpus: components["schemas"]["CorpusQuerySignals"] | null;
            /**
             * Analysis Hash
             * @description Hash of everything above; equal inputs, equal hash
             */
            analysis_hash: string;
        };
        /**
         * QueryClass
         * @enum {string}
         */
        QueryClass: "lexical" | "semantic" | "mixed";
        /**
         * QueryFeatures
         * @description Measured properties of the query text. Every list keeps first-occurrence order.
         */
        QueryFeatures: {
            /** Char Count */
            char_count: number;
            /**
             * Token Count
             * @description Word tokens (Unicode word characters)
             */
            token_count: number;
            /**
             * Bm25 Terms
             * @description Distinct terms BM25 searches (its analyzer)
             */
            bm25_terms: string[];
            /**
             * Key Terms
             * @description bm25_terms that are not function words
             */
            key_terms: string[];
            /**
             * Function Word Ratio
             * @description Share of word tokens that are function words (stopwords, interrogatives, auxiliaries, pronouns, prepositions)
             */
            function_word_ratio: number;
            /**
             * Is Question
             * @description Ends with '?' or starts with a question/request word
             */
            is_question: boolean;
            /**
             * Question Word
             * @description The leading question or request word
             */
            question_word: string | null;
            question_type: components["schemas"]["QuestionType"];
            /** Quoted Phrases */
            quoted_phrases: string[];
            /**
             * Identifiers
             * @description Tokens with digits, inner capitals, underscores, dots or 2+ capitals
             */
            identifiers: string[];
            /**
             * Capitalized Terms
             * @description Capitalised words not at sentence start
             */
            capitalized_terms: string[];
            /** Numbers */
            numbers: string[];
            /**
             * Entities
             * @description Quoted phrases, identifiers and capitalised terms
             */
            entities: string[];
            /**
             * Concept Segments
             * @description Parts split on and/or/vs/commas/semicolons that contain a key term
             */
            concept_segments: string[];
            /** Comparison Markers */
            comparison_markers: string[];
            /** Multi Hop Markers */
            multi_hop_markers: string[];
            /** Temporal Markers */
            temporal_markers: string[];
            /** Negation Markers */
            negation_markers: string[];
            /** Ambiguity Markers */
            ambiguity_markers: string[];
        };
        /** QueryLabels */
        QueryLabels: {
            query_class: components["schemas"]["QueryClass"];
            /**
             * Class Margin
             * @description lexical - semantic score; |margin| is the class confidence, not a probability
             */
            class_margin: number;
            complexity: components["schemas"]["Complexity"];
            /** Multi Hop Likely */
            multi_hop_likely: boolean;
            /** Ambiguous */
            ambiguous: boolean;
            evidence_need: components["schemas"]["EvidenceNeed"];
        };
        /**
         * QuerySignal
         * @description A 0..1 score that is exactly the clipped sum of its listed contributions.
         */
        QuerySignal: {
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Contributions */
            contributions: components["schemas"]["SignalContribution"][];
        };
        /**
         * QuestionType
         * @enum {string}
         */
        QuestionType: "definition" | "procedural" | "explanatory" | "comparison" | "list" | "boolean" | "factoid" | "keyword";
        /**
         * RankMovement
         * @enum {string}
         */
        RankMovement: "promoted" | "demoted" | "unchanged";
        /**
         * RerankCandidate
         * @description One scored candidate, including those that did not make the final top-k.
         */
        RerankCandidate: {
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Chunk Ordinal */
            chunk_ordinal: number;
            rerank: components["schemas"]["RerankDetail"];
        };
        /**
         * RerankConfiguration
         * @description The resolved reranking step: which model scored how many upstream candidates.
         */
        RerankConfiguration: {
            reranker: components["schemas"]["RerankerSpec"];
            /** Candidate K */
            candidate_k: number;
        };
        /**
         * RerankDetail
         * @description How the reranker moved one candidate. Ranks are 1-based positions in the candidate pool.
         */
        RerankDetail: {
            /**
             * Original Rank
             * @description Rank in the upstream retrieval
             */
            original_rank: number;
            /**
             * Original Score
             * @description The upstream retriever's own score
             */
            original_score: number;
            /** Reranker Score */
            reranker_score: number;
            /**
             * Final Rank
             * @description Rank after reranking the whole candidate pool
             */
            final_rank: number;
            /**
             * Rank Delta
             * @description original_rank - final_rank; positive = moved up
             */
            rank_delta: number;
            movement: components["schemas"]["RankMovement"];
            /**
             * Entered Top K
             * @description In the final top-k but not the upstream top-k
             */
            entered_top_k: boolean;
            /**
             * Left Top K
             * @description In the upstream top-k but not the final top-k
             */
            left_top_k: boolean;
        };
        /** RerankParams */
        "RerankParams-Input": {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Model
             * @description A registered reranker model
             * @default cross-encoder/ms-marco-MiniLM-L-6-v2
             */
            model: string;
            /**
             * Candidate K
             * @description Upstream candidates the reranker scores
             * @default 50
             */
            candidate_k: number;
        };
        /** RerankParams */
        "RerankParams-Output": {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Model
             * @description A registered reranker model
             * @default cross-encoder/ms-marco-MiniLM-L-6-v2
             */
            model: string;
            /**
             * Candidate K
             * @description Upstream candidates the reranker scores
             * @default 50
             */
            candidate_k: number;
        };
        /** RerankProvenance */
        RerankProvenance: {
            /** Reranker */
            reranker: string;
            info: components["schemas"]["RerankerInfo"];
            /** Reranker Config Hash */
            reranker_config_hash: string;
            /** Candidate K */
            candidate_k: number;
            /** Final Top K */
            final_top_k: number;
            /**
             * Candidates Scored
             * @description May be below candidate_k on small corpora
             */
            candidates_scored: number;
            /** @description The unreranked retrieval that produced the pool (top_k = candidate_k) */
            upstream_configuration: components["schemas"]["RetrievalConfiguration"];
            /** Upstream Configuration Hash */
            upstream_configuration_hash: string;
            /**
             * Latency Ms
             * @description Scoring time only; excludes the one-time model load
             */
            latency_ms: number;
            /**
             * Statistics
             * @description promoted, demoted, unchanged, entered_top_k, left_top_k over the whole pool
             */
            statistics: {
                [key: string]: number;
            };
        };
        /** RerankReport */
        RerankReport: {
            /**
             * Candidates
             * @description The whole scored pool, by final rank
             */
            candidates: components["schemas"]["RerankCandidate"][];
        };
        /**
         * RerankerInfo
         * @description The spec plus facts read from the loaded model files.
         */
        RerankerInfo: {
            spec: components["schemas"]["RerankerSpec"];
            /** Config Hash */
            config_hash: string;
            /**
             * Scoring
             * @description How a (query, passage) pair becomes a score
             */
            scoring: string;
            /**
             * Activation
             * @description Applied to the model's single logit: identity or sigmoid
             */
            activation: string;
            /** Max Seq Length */
            max_seq_length: number;
            /** Truncation */
            truncation: string;
            /** Weights Sha256 */
            weights_sha256: string;
        };
        /**
         * RerankerSpec
         * @description What determines a reranker's scores. Its hash is part of every reranked configuration.
         */
        RerankerSpec: {
            /**
             * Provider
             * @default onnx-cross-encoder
             */
            provider: string;
            /**
             * Model
             * @default cross-encoder/ms-marco-MiniLM-L-6-v2
             */
            model: string;
            /**
             * Revision
             * @description Pinned model commit
             * @default 233902d25c440f23af6f7d6e94d2946bac0bee0a
             */
            revision: string;
            /**
             * Max Seq Length
             * @description None = the model's own limit
             */
            max_seq_length: number | null;
            /**
             * Batch Size
             * @default 32
             */
            batch_size: number;
        };
        /**
         * RetrievalConfiguration
         * @description Everything that determines a ranked result set, resolved. The unit an experiment varies.
         */
        RetrievalConfiguration: {
            /** Corpus Id */
            corpus_id: string;
            /** Corpus Version */
            corpus_version: number;
            /** Chunking Hash */
            chunking_hash: string;
            strategy: components["schemas"]["RetrievalStrategy"];
            /** Top K */
            top_k: number;
            bm25: components["schemas"]["Bm25Params-Output"] | null;
            embedder: components["schemas"]["EmbedderSpec"] | null;
            hybrid: components["schemas"]["HybridParams-Output"] | null;
            rerank: components["schemas"]["RerankConfiguration"] | null;
            routing: components["schemas"]["RoutingConfiguration"] | null;
        };
        /** RetrievalEvaluationRequest */
        RetrievalEvaluationRequest: {
            /** Ranked Ids */
            ranked_ids: string[];
            /**
             * Relevance
             * @description Graded relevance judgements; grade > 0 counts as relevant.
             */
            relevance: {
                [key: string]: number;
            };
            /**
             * Ks
             * @default [
             *       1,
             *       5,
             *       10
             *     ]
             */
            ks: number[];
        };
        /** RetrievalEvaluationResponse */
        RetrievalEvaluationResponse: {
            /** Metrics */
            metrics: components["schemas"]["Metric"][];
        };
        /**
         * RetrievalHit
         * @description One retrieved chunk with everything needed to display and trace it.
         */
        RetrievalHit: {
            result: components["schemas"]["RetrievalResult"];
            chunk: components["schemas"]["Chunk"];
            /** Filename */
            filename: string;
            /** Media Type */
            media_type: string;
            /** Document Version */
            document_version: number;
            /** Matched Terms */
            matched_terms: string[];
            /** @description Hybrid only */
            fusion: components["schemas"]["FusionDetail"] | null;
            /** @description Reranked requests only */
            rerank: components["schemas"]["RerankDetail"] | null;
        };
        /**
         * RetrievalMode
         * @enum {string}
         */
        RetrievalMode: "manual" | "adaptive";
        /** RetrievalProvenance */
        RetrievalProvenance: {
            /** Corpus Id */
            corpus_id: string;
            /** Corpus Version */
            corpus_version: number;
            /** Chunking Hash */
            chunking_hash: string;
            strategy: components["schemas"]["RetrievalStrategy"];
            /** Retriever */
            retriever: string;
            /** Retriever Config */
            retriever_config: {
                [key: string]: unknown;
            };
            /** Retriever Config Hash */
            retriever_config_hash: string;
            configuration: components["schemas"]["RetrievalConfiguration"];
            /** Configuration Hash */
            configuration_hash: string;
            /**
             * Index Id
             * @description Dense index used, if any
             */
            index_id: string | null;
            /** Query Terms */
            query_terms: string[];
            /**
             * Statistics
             * @description Retriever-specific, e.g. candidate_chunks, avg_chunk_length, indexed_now
             */
            statistics: {
                [key: string]: number;
            };
            environment: components["schemas"]["EnvironmentSnapshot"];
            /** Elapsed Ms */
            elapsed_ms: number;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** @description Reranked requests only */
            reranking: components["schemas"]["RerankProvenance"] | null;
            /** @description Adaptive requests only */
            routing: components["schemas"]["RoutingProvenance"] | null;
        };
        /** RetrievalRequest */
        "RetrievalRequest-Input": {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
            /**
             * Version
             * @description Corpus version; default current
             */
            version?: number | null;
            /** @default sparse */
            strategy: components["schemas"]["RetrievalStrategy"];
            bm25?: components["schemas"]["Bm25Params-Input"];
            hybrid?: components["schemas"]["HybridParams-Input"];
            rerank?: components["schemas"]["RerankParams-Input"];
            /**
             * @description adaptive: the router replaces strategy, hybrid and rerank
             * @default manual
             */
            mode: components["schemas"]["RetrievalMode"];
            router?: components["schemas"]["RouterParams-Input"];
        };
        /** RetrievalRequest */
        "RetrievalRequest-Output": {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
            /**
             * Version
             * @description Corpus version; default current
             */
            version: number | null;
            /** @default sparse */
            strategy: components["schemas"]["RetrievalStrategy"];
            bm25: components["schemas"]["Bm25Params-Output"];
            hybrid: components["schemas"]["HybridParams-Output"];
            rerank: components["schemas"]["RerankParams-Output"];
            /**
             * @description adaptive: the router replaces strategy, hybrid and rerank
             * @default manual
             */
            mode: components["schemas"]["RetrievalMode"];
            router: components["schemas"]["RouterParams-Output"];
        };
        /** RetrievalResponse */
        RetrievalResponse: {
            query: components["schemas"]["Query"];
            /**
             * Hits
             * @description Final ranking; when reranked, result.rank and result.score are the reranker's
             */
            hits: components["schemas"]["RetrievalHit"][];
            provenance: components["schemas"]["RetrievalProvenance"];
            /** Warnings */
            warnings: string[];
            /** @description Reranked requests only */
            reranking: components["schemas"]["RerankReport"] | null;
        };
        /** RetrievalResult */
        RetrievalResult: {
            /** Query Id */
            query_id: string;
            strategy: components["schemas"]["RetrievalStrategy"];
            /** Retriever */
            retriever: string;
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string;
            /** Document Version Id */
            document_version_id: string;
            /** Rank */
            rank: number;
            /** Score */
            score: number;
            /** @default retrieved */
            origin: components["schemas"]["ContentOrigin"];
        };
        /**
         * RetrievalStrategy
         * @enum {string}
         */
        RetrievalStrategy: "sparse" | "dense" | "hybrid" | "metadata" | "graph" | "multi_hop" | "decomposition" | "multimodal";
        /** RouteAlternative */
        RouteAlternative: {
            option: components["schemas"]["RouteOption"];
            /** Selected */
            selected: boolean;
            /** Available */
            available: boolean;
            /** Unavailable Reason */
            unavailable_reason: string | null;
            /**
             * Rules
             * @description Policy rules that select this option
             */
            rules: string[];
        };
        /**
         * RouteOption
         * @enum {string}
         */
        RouteOption: "sparse" | "dense" | "hybrid_rrf" | "hybrid_weighted";
        /** RouterDecision */
        RouterDecision: {
            /** Id */
            id: string;
            /** Query Id */
            query_id: string;
            /** Policy */
            policy: string;
            /** Policy Version */
            policy_version: string;
            /** Policy Config Hash */
            policy_config_hash: string;
            /** Analysis Hash */
            analysis_hash: string;
            /** @description The selected retrieval option */
            option: components["schemas"]["RouteOption"];
            /** @description The policy's choice before availability */
            preferred: components["schemas"]["RouteOption"];
            strategy: components["schemas"]["RetrievalStrategy"];
            hybrid: components["schemas"]["HybridParams-Output"] | null;
            rerank: components["schemas"]["RerankParams-Output"];
            /**
             * Rules
             * @description Strategy rules in order, to the first match
             */
            rules: components["schemas"]["RuleEvaluation"][];
            /**
             * Rerank Rules
             * @description Rerank rules, to the first match
             */
            rerank_rules: components["schemas"]["RuleEvaluation"][];
            /** Alternatives */
            alternatives: components["schemas"]["RouteAlternative"][];
            /**
             * Margin
             * @description The deciding rule's margin; small = near a boundary
             */
            margin: number | null;
            /**
             * Rationale
             * @description The fired rules, filled in with measured values
             */
            rationale: string[];
            /**
             * Configuration Hash
             * @description Hash of the selected configuration, as the same manual request reports it
             */
            configuration_hash: string;
            /**
             * Decision Hash
             * @description Hash of the decision, excluding ids and timestamps
             */
            decision_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RouterParams */
        "RouterParams-Input": {
            /**
             * Analyzer
             * @description A registered query analyzer
             * @default heuristic
             */
            analyzer: string;
            /**
             * Policy
             * @description A registered router policy
             * @default rules-baseline
             */
            policy: string;
        };
        /** RouterParams */
        "RouterParams-Output": {
            /**
             * Analyzer
             * @description A registered query analyzer
             * @default heuristic
             */
            analyzer: string;
            /**
             * Policy
             * @description A registered router policy
             * @default rules-baseline
             */
            policy: string;
        };
        /** RouterRequest */
        RouterRequest: {
            /** Corpus Id */
            corpus_id: string;
            /** Query */
            query: string;
            /**
             * Version
             * @description Corpus version; default current
             */
            version?: number | null;
            /**
             * Top K
             * @description The final top-k the route must serve
             * @default 10
             */
            top_k: number;
            router?: components["schemas"]["RouterParams-Input"];
        };
        /** RouterResponse */
        RouterResponse: {
            query: components["schemas"]["Query"];
            /** @description The manual request the router selected: sending it reproduces the route */
            request: components["schemas"]["RetrievalRequest-Output"];
            routing: components["schemas"]["RoutingProvenance"];
        };
        /**
         * RoutingConfiguration
         * @description The identity of the routing step: which analyzer and policy, at which versions.
         */
        RoutingConfiguration: {
            /** Analyzer */
            analyzer: string;
            /** Analyzer Version */
            analyzer_version: string;
            /** Analyzer Config Hash */
            analyzer_config_hash: string;
            /** Policy */
            policy: string;
            /** Policy Version */
            policy_version: string;
            /** Policy Config Hash */
            policy_config_hash: string;
        };
        /** RoutingProvenance */
        RoutingProvenance: {
            routing: components["schemas"]["RoutingConfiguration"];
            /** Routing Hash */
            routing_hash: string;
            analysis: components["schemas"]["QueryAnalysis"];
            decision: components["schemas"]["RouterDecision"];
            /**
             * Analysis Ms
             * @description Query analysis, including corpus term statistics
             */
            analysis_ms: number;
            /** Decision Ms */
            decision_ms: number;
        };
        /**
         * RuleEvaluation
         * @description One policy rule as evaluated for this query: what it read and whether it fired.
         */
        RuleEvaluation: {
            /** Rule */
            rule: string;
            /**
             * Description
             * @description The rule as written in the policy
             */
            description: string;
            /** Matched */
            matched: boolean;
            /** Inputs */
            inputs: {
                [key: string]: number | string | boolean | null;
            };
            /**
             * Margin
             * @description Distance of the inputs from the nearest threshold of the rule
             */
            margin: number | null;
            /**
             * Outcome
             * @description What the rule selects when it fires
             */
            outcome: string | null;
        };
        /** SignalContribution */
        SignalContribution: {
            /** Feature */
            feature: string;
            /**
             * Value
             * @description The feature's value, scaled to 0..1
             */
            value: number;
            /** Weight */
            weight: number;
            /**
             * Contribution
             * @description value * weight
             */
            contribution: number;
        };
        /** SupportedFormat */
        SupportedFormat: {
            /** Media Type */
            media_type: string;
            /** Extensions */
            extensions: string[];
            /** Parser */
            parser: string;
        };
        /** TermStatistic */
        TermStatistic: {
            /** Term */
            term: string;
            /**
             * Document Frequency
             * @description Chunks in the corpus version containing it
             */
            document_frequency: number;
            /**
             * Idf
             * @description BM25 idf in this corpus version
             */
            idf: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionChange */
        VersionChange: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            change: components["schemas"]["FileOutcome"];
            /** Document Version Id */
            document_version_id: string | null;
            /** Previous Document Version Id */
            previous_document_version_id: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    environment_api_v1_provenance_environment_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponse"];
                };
            };
        };
    };
    decide_api_v1_router_decide_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotImplementedDetail"];
                };
            };
        };
    };
    list_experiments_api_v1_experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experiment"][];
                };
            };
        };
    };
    create_experiment_api_v1_experiments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experiment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRun"][];
                };
            };
        };
    };
    evaluate_retrieval_api_v1_evaluation_retrieval_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrievalEvaluationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalEvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    supported_formats_api_v1_ingestion_formats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportedFormat"][];
                };
            };
        };
    };
    list_corpora_api_v1_corpora_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusSummary"][];
                };
            };
        };
    };
    create_corpus_api_v1_corpora_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorpusCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_corpus_api_v1_corpora__corpus_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_corpora__corpus_id__documents_get: {
        parameters: {
            query?: {
                /** @description Defaults to current */
                version?: number | null;
            };
            header?: never;
            path: {
                corpus_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_documents_api_v1_corpora__corpus_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_documents_api_v1_corpora__corpus_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_corpora__corpus_id__documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_document_api_v1_corpora__corpus_id__documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chunks_api_v1_document_versions__version_id__chunks_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_v1_corpora__corpus_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusVersion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_changes_api_v1_corpora__corpus_id__versions__version__changes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionChange"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ingestions_api_v1_corpora__corpus_id__ingestions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_api_v1_corpora__corpus_id__retrieve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrievalRequest-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotImplementedDetail"];
                };
            };
        };
    };
    dense_index_status_api_v1_corpora__corpus_id__dense_index_get: {
        parameters: {
            query?: {
                /** @description Defaults to current */
                version?: number | null;
            };
            header?: never;
            path: {
                corpus_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DenseIndexView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_dense_index_api_v1_corpora__corpus_id__dense_index_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DenseIndexBuild"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DenseIndexView"];
                };
            };
            /** @description Build started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DenseIndexView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
