/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/provenance/environment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Environment */
        get: operations["environment_api_v1_provenance_environment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpora": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Corpora */
        get: operations["list_corpora_api_v1_corpora_get"];
        put?: never;
        /** Create Corpus */
        post: operations["create_corpus_api_v1_corpora_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpora/{corpus_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Corpus */
        get: operations["get_corpus_api_v1_corpora__corpus_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpora/{corpus_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Document */
        post: operations["ingest_document_api_v1_corpora__corpus_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/retrieval/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_api_v1_retrieval_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/router/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide */
        post: operations["decide_api_v1_router_decide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Experiments */
        get: operations["list_experiments_api_v1_experiments_get"];
        put?: never;
        /** Create Experiment */
        post: operations["create_experiment_api_v1_experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation/retrieval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate Retrieval */
        post: operations["evaluate_retrieval_api_v1_evaluation_retrieval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ComponentHealth */
        ComponentHealth: {
            /** Name */
            name: string;
            state: components["schemas"]["ComponentState"];
            /** Detail */
            detail: string;
        };
        /**
         * ComponentState
         * @enum {string}
         */
        ComponentState: "ok" | "not_configured" | "error";
        /**
         * ContentOrigin
         * @description Where a piece of information came from. Every value shown to a user carries one.
         * @enum {string}
         */
        ContentOrigin: "retrieved" | "inferred" | "generated" | "measured" | "simulated";
        /** Corpus */
        Corpus: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Version
             * @default 0
             */
            version: number;
            /**
             * Document Count
             * @default 0
             */
            document_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CorpusCreate */
        CorpusCreate: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** DocumentIngestRequest */
        DocumentIngestRequest: {
            /** Source Uri */
            source_uri: string;
            /** Media Type */
            media_type?: string | null;
        };
        /** EnvironmentResponse */
        EnvironmentResponse: {
            environment: components["schemas"]["EnvironmentSnapshot"];
        };
        /** EnvironmentSnapshot */
        EnvironmentSnapshot: {
            /** Rag Forge Version */
            rag_forge_version: string;
            /** Python Version */
            python_version: string;
            /** Platform */
            platform: string;
            /** Git Commit */
            git_commit: string | null;
            /** Packages */
            packages: {
                [key: string]: string;
            };
        };
        /** Experiment */
        Experiment: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Hypothesis
             * @default
             */
            hypothesis: string;
            /** Corpus Id */
            corpus_id: string | null;
            /** Configuration Ids */
            configuration_ids: string[];
            /** @default draft */
            status: components["schemas"]["ExperimentStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ExperimentCreate */
        ExperimentCreate: {
            /** Name */
            name: string;
            /**
             * Hypothesis
             * @default
             */
            hypothesis: string;
            /** Corpus Id */
            corpus_id?: string | null;
        };
        /** ExperimentRun */
        ExperimentRun: {
            /** Id */
            id: string;
            /** Experiment Id */
            experiment_id: string;
            /** Configuration Id */
            configuration_id: string;
            /** Config Hash */
            config_hash: string;
            /** @default queued */
            status: components["schemas"]["ExperimentStatus"];
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Provenance Id */
            provenance_id: string | null;
        };
        /**
         * ExperimentStatus
         * @enum {string}
         */
        ExperimentStatus: "draft" | "queued" | "running" | "completed" | "failed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Components */
            components: components["schemas"]["ComponentHealth"][];
        };
        /** Metric */
        Metric: {
            /** Name */
            name: string;
            /** Value */
            value: number;
            /** K */
            k: number | null;
            /** @default measured */
            origin: components["schemas"]["ContentOrigin"];
        };
        /** NotImplementedDetail */
        NotImplementedDetail: {
            /** Capability */
            capability: string;
            /** Message */
            message: string;
        };
        /** Query */
        Query: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RetrievalEvaluationRequest */
        RetrievalEvaluationRequest: {
            /** Ranked Ids */
            ranked_ids: string[];
            /**
             * Relevance
             * @description Graded relevance judgements; grade > 0 counts as relevant.
             */
            relevance: {
                [key: string]: number;
            };
            /**
             * Ks
             * @default [
             *       1,
             *       5,
             *       10
             *     ]
             */
            ks: number[];
        };
        /** RetrievalEvaluationResponse */
        RetrievalEvaluationResponse: {
            /** Metrics */
            metrics: components["schemas"]["Metric"][];
        };
        /** RetrievalRequest */
        RetrievalRequest: {
            /** Corpus Id */
            corpus_id: string;
            /** Query */
            query: string;
            /** Strategies */
            strategies: components["schemas"]["RetrievalStrategy"][];
            /**
             * Top K
             * @default 10
             */
            top_k: number;
        };
        /** RetrievalResponse */
        RetrievalResponse: {
            query: components["schemas"]["Query"];
            /** Results */
            results: components["schemas"]["RetrievalResult"][];
        };
        /** RetrievalResult */
        RetrievalResult: {
            /** Query Id */
            query_id: string;
            strategy: components["schemas"]["RetrievalStrategy"];
            /** Retriever */
            retriever: string;
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string;
            /** Rank */
            rank: number;
            /** Score */
            score: number;
            /** @default retrieved */
            origin: components["schemas"]["ContentOrigin"];
        };
        /**
         * RetrievalStrategy
         * @enum {string}
         */
        RetrievalStrategy: "sparse" | "dense" | "hybrid" | "metadata" | "graph" | "multi_hop" | "decomposition" | "multimodal";
        /** RouterDecision */
        RouterDecision: {
            /** Id */
            id: string;
            /** Query Id */
            query_id: string;
            /** Policy */
            policy: string;
            /** Query Features */
            query_features: {
                [key: string]: unknown;
            };
            /** Selected Strategies */
            selected_strategies: components["schemas"]["RetrievalStrategy"][];
            /** Rationale */
            rationale: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RouterRequest */
        RouterRequest: {
            /** Corpus Id */
            corpus_id: string;
            /** Query */
            query: string;
            /** Policy */
            policy: string;
        };
        /** RouterResponse */
        RouterResponse: {
            query: components["schemas"]["Query"];
            decision: components["schemas"]["RouterDecision"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    environment_api_v1_provenance_environment_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponse"];
                };
            };
        };
    };
    list_corpora_api_v1_corpora_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Corpus"][];
                };
            };
        };
    };
    create_corpus_api_v1_corpora_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorpusCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Corpus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_corpus_api_v1_corpora__corpus_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Corpus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_document_api_v1_corpora__corpus_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotImplementedDetail"];
                };
            };
        };
    };
    search_api_v1_retrieval_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrievalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotImplementedDetail"];
                };
            };
        };
    };
    decide_api_v1_router_decide_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotImplementedDetail"];
                };
            };
        };
    };
    list_experiments_api_v1_experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experiment"][];
                };
            };
        };
    };
    create_experiment_api_v1_experiments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experiment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRun"][];
                };
            };
        };
    };
    evaluate_retrieval_api_v1_evaluation_retrieval_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrievalEvaluationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalEvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
